# Generated by Django 5.1.3 on 2025-11-19 19:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='breves/', verbose_name='Imagen')),
                ('icono', models.CharField(blank=True, help_text='Ej: fa fa-heart, bi bi-house', max_length=100, verbose_name='Ícono (clase CSS)')),
                ('enlace', models.CharField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Enlace')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Breve',
                'verbose_name_plural': 'Breves',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='DatosIce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de contacto')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('facebook', models.CharField(blank=True, max_length=300, verbose_name='Facebook URL')),
                ('twitter', models.CharField(blank=True, max_length=300, verbose_name='Twitter URL')),
                ('youtube', models.CharField(blank=True, max_length=300, verbose_name='YouTube URL')),
                ('instagram', models.CharField(blank=True, max_length=300, verbose_name='Instagram URL')),
                ('stream_youtube', models.CharField(blank=True, max_length=500, verbose_name='Stream en vivo YouTube')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Datos de ICE',
                'verbose_name_plural': 'Datos de ICE',
            },
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='galeria/', verbose_name='Imagen')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Galería',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.IntegerField(choices=[(1, 'Fundamento (Mensaje escrito)'), (2, 'Video')], default=1, verbose_name='Tipo de mensaje')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor/Predicador')),
                ('introduccion', models.TextField(verbose_name='Introducción')),
                ('contenido', models.TextField(blank=True, help_text='Solo para mensajes escritos', verbose_name='Contenido completo')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mensajes/', verbose_name='Imagen')),
                ('enlace_video', models.CharField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Enlace del video (YouTube/Vimeo)')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('tipo', models.IntegerField(choices=[(1, 'Noticia'), (2, 'Boletín')], default=1, verbose_name='Tipo')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('introduccion', models.TextField(verbose_name='Introducción')),
                ('contenido', models.TextField(verbose_name='Contenido completo')),
                ('imagen_principal', models.ImageField(upload_to='noticias/', verbose_name='Imagen principal')),
                ('imagen_secundaria', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen secundaria')),
                ('fecha_publicacion', models.DateField(verbose_name='Fecha de publicación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.CharField(blank=True, max_length=300, verbose_name='Descripción breve')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='paginas/', verbose_name='Imagen')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='slider/', verbose_name='Imagen')),
                ('enlace', models.CharField(blank=True, max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='Enlace (URL)')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('pagina', models.ForeignKey(blank=True, help_text='Si no hay URL externa, enlazar a página interna', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenido.pagina', verbose_name='Página interna')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['orden'],
            },
        ),
    ]
