# Generated by Django 5.1.3 on 2025-11-20 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ofrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('banco', models.CharField(blank=True, max_length=200, verbose_name='Nombre del banco')),
                ('cuenta', models.CharField(blank=True, max_length=200, verbose_name='Número de cuenta')),
                ('titular', models.CharField(blank=True, max_length=200, verbose_name='Titular de la cuenta')),
                ('mercadopago_link', models.CharField(blank=True, max_length=500, verbose_name='Link de Mercado Pago')),
                ('mercadopago_alias', models.CharField(blank=True, max_length=100, verbose_name='Alias de Mercado Pago')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden de visualización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ofrenda',
                'verbose_name_plural': 'Ofrendas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=300, verbose_name='Subtítulo')),
                ('contenido', models.TextField(help_text='Puede usar HTML', verbose_name='Contenido')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='secciones/', verbose_name='Imagen')),
                ('tipo', models.CharField(choices=[('texto', 'Solo Texto'), ('texto_imagen', 'Texto con Imagen'), ('cards', 'Tarjetas/Cards')], default='texto', max_length=20, verbose_name='Tipo de sección')),
                ('estilo', models.CharField(choices=[('light', 'Fondo Claro'), ('dark', 'Fondo Oscuro'), ('primary', 'Color Primario'), ('secondary', 'Color Secundario')], default='light', max_length=20, verbose_name='Estilo de fondo')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden en homepage')),
                ('mostrar_en_home', models.BooleanField(default=True, verbose_name='Mostrar en inicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['orden', 'titulo'],
            },
        ),
    ]
