# Generated by Django 5.1.3 on 2025-11-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0002_ofrenda_seccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagen principal'),
        ),
    ]
