# Generated by Django 5.1.3 on 2025-11-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0003_alter_noticia_imagen_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='vistas',
            field=models.PositiveIntegerField(default=0, verbose_name='Visitas'),
        ),
    ]
