# Generated by Django 5.1.3 on 2025-12-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0004_noticia_vistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.TextField(blank=True, verbose_name='Contenido completo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='introduccion',
            field=models.TextField(blank=True, verbose_name='Introducción'),
        ),
    ]
