# Generated by Django 5.1.3 on 2025-12-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0005_alter_noticia_contenido_alter_noticia_introduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosice',
            name='codigo_acceso_miembros',
            field=models.CharField(blank=True, default='ICE2024', help_text='Código que los miembros deben ingresar para actualizar sus datos', max_length=50, verbose_name='Código de acceso para miembros'),
        ),
    ]
