# Generated by Django 5.1.3 on 2025-12-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0006_add_codigo_acceso_miembros'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosice',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Numero con codigo de pais sin + ni espacios (ej: 595981123456)', max_length=20, verbose_name='WhatsApp'),
        ),
    ]
