# Generated by Django 5.1.3 on 2025-12-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0007_add_whatsapp_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosice',
            name='chat_habilitado',
            field=models.BooleanField(default=False, help_text='Habilitar el chat con el asistente virtual en el sitio público', verbose_name='Chat habilitado'),
        ),
    ]
