# Generated by Django 5.1.3 on 2025-12-23 16:37

import django.db.models.deletion
from django.db import migrations, models


def create_tipos_mensaje(apps, schema_editor):
    """Crear los tipos de mensaje por defecto ANTES de la FK"""
    TipoMensaje = apps.get_model('contenido', 'TipoMensaje')

    # Crear los tipos originales con IDs específicos
    TipoMensaje.objects.get_or_create(
        id=1,
        defaults={'nombre': 'Fundamento (Mensaje escrito)', 'color': 'bg-success', 'orden': 1}
    )
    TipoMensaje.objects.get_or_create(
        id=2,
        defaults={'nombre': 'Video', 'color': 'bg-danger', 'orden': 2}
    )


def reverse_tipos(apps, schema_editor):
    """No hacer nada en reverse - la tabla se elimina"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0008_add_chat_habilitado'),
    ]

    operations = [
        # 1. Crear el modelo TipoMensaje
        migrations.CreateModel(
            name='TipoMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('color', models.CharField(default='bg-primary', help_text='Ej: bg-primary, bg-success, bg-danger, bg-warning, bg-info', max_length=20, verbose_name='Color (clase Bootstrap)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Mensaje',
                'verbose_name_plural': 'Tipos de Mensaje',
                'ordering': ['orden', 'nombre'],
            },
        ),
        # 2. Insertar los datos de tipos ANTES de crear la FK
        migrations.RunPython(create_tipos_mensaje, reverse_tipos),
        # 3. Ahora sí alterar el campo a FK
        migrations.AlterField(
            model_name='mensaje',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenido.tipomensaje', verbose_name='Tipo de mensaje'),
        ),
    ]
