# Generated by Django 5.1.3 on 2025-12-23 16:38

from django.db import migrations


def create_tipos_mensaje(apps, schema_editor):
    """Crear los tipos de mensaje por defecto"""
    TipoMensaje = apps.get_model('contenido', 'TipoMensaje')

    # Crear los tipos originales
    TipoMensaje.objects.get_or_create(
        id=1,
        defaults={'nombre': 'Fundamento (Mensaje escrito)', 'color': 'bg-success', 'orden': 1}
    )
    TipoMensaje.objects.get_or_create(
        id=2,
        defaults={'nombre': 'Video', 'color': 'bg-danger', 'orden': 2}
    )


def reverse_tipos(apps, schema_editor):
    """Eliminar los tipos creados"""
    TipoMensaje = apps.get_model('contenido', 'TipoMensaje')
    TipoMensaje.objects.filter(id__in=[1, 2]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_tipomensaje_alter_mensaje_tipo'),
    ]

    operations = [
        migrations.RunPython(create_tipos_mensaje, reverse_tipos),
    ]
