# Generated by Django 5.1.3 on 2025-12-23

from django.db import migrations


def fix_sequence(apps, schema_editor):
    """Resetear la secuencia de ID después de insertar registros con IDs específicos"""
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            cursor.execute("""
                SELECT setval(
                    pg_get_serial_sequence('contenido_tipomensaje', 'id'),
                    COALESCE(MAX(id), 1)
                ) FROM contenido_tipomensaje;
            """)


def reverse_fix(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contenido', '0009_tipomensaje_alter_mensaje_tipo'),
    ]

    operations = [
        migrations.RunPython(fix_sequence, reverse_fix),
    ]
