# Generated by Django 5.1.3 on 2026-03-23 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la clase')),
                ('color', models.CharField(help_text='Ej: verde, azul, amarilla', max_length=20, verbose_name='Color')),
                ('emoji', models.CharField(blank=True, max_length=10, verbose_name='Emoji')),
                ('edad_desde', models.PositiveIntegerField(verbose_name='Edad desde')),
                ('edad_hasta', models.PositiveIntegerField(blank=True, help_text='Dejar vacío para "en adelante"', null=True, verbose_name='Edad hasta')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: 1ro, 2do y 3er grado', max_length=300, verbose_name='Descripción')),
                ('maestros', models.CharField(blank=True, max_length=300, verbose_name='Maestros')),
                ('codigo_acceso', models.CharField(help_text='Código que usan los maestros para entrar', max_length=20, verbose_name='Código de acceso')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['orden', 'edad_desde'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('grado_nivel', models.CharField(blank=True, choices=[('', 'Sin especificar'), ('jardin', 'Jardín'), ('preescolar', 'Preescolar'), ('1_primaria', '1° Primaria'), ('2_primaria', '2° Primaria'), ('3_primaria', '3° Primaria'), ('4_primaria', '4° Primaria'), ('5_primaria', '5° Primaria'), ('6_primaria', '6° Primaria'), ('1_secundaria', '1° Secundaria'), ('2_secundaria', '2° Secundaria'), ('3_secundaria', '3° Secundaria'), ('4_secundaria', '4° Secundaria'), ('5_secundaria', '5° Secundaria'), ('6_secundaria', '6° Secundaria'), ('terciario', 'Terciario'), ('universitario', 'Universitario'), ('trabajando', 'Trabajando')], max_length=20, verbose_name='Grado/Nivel')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='escuela.claseescuela', verbose_name='Clase')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
