# Generated by Django 5.1.3 on 2026-04-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0002_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomingoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha (domingo)')),
                ('motivo', models.CharField(help_text='Ej: Santa Cena, Culto especial, etc.', max_length=200, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Domingo excluido',
                'verbose_name_plural': 'Domingos excluidos',
                'ordering': ['-fecha'],
            },
        ),
    ]
