# Generated by Django 5.1.3 on 2026-04-27 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_domingoexcluido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('archivo', models.FileField(upload_to='proyecciones/', verbose_name='Archivo PDF')),
                ('codigo', models.CharField(blank=True, help_text='Codigo corto para la URL publica', max_length=10, unique=True, verbose_name='Codigo de acceso')),
                ('total_slides', models.PositiveIntegerField(default=1, verbose_name='Total de slides')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Presentacion',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadoProyeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_actual', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('presentacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado', to='escuela.presentacion')),
            ],
            options={
                'verbose_name': 'Estado de proyeccion',
                'verbose_name_plural': 'Estados de proyeccion',
            },
        ),
    ]
