# Generated by Django 5.1.3 on 2025-11-19 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Clase')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Estado civil')),
            ],
            options={
                'verbose_name': 'Estado civil',
                'verbose_name_plural': 'Estados civiles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Grupo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Hermano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('cumpleaños', models.DateField(blank=True, help_text='Solo mes y día (año puede ser ficticio)', null=True, verbose_name='Cumpleaños')),
                ('telefono_fijo', models.CharField(blank=True, max_length=50, verbose_name='Teléfono fijo')),
                ('celular', models.CharField(blank=True, max_length=50, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('localidad', models.CharField(blank=True, max_length=200, verbose_name='Localidad')),
                ('domicilio', models.CharField(blank=True, max_length=300, verbose_name='Domicilio')),
                ('barrio', models.CharField(blank=True, max_length=200, verbose_name='Barrio')),
                ('marca_1', models.BooleanField(default=False, verbose_name='Marca 1')),
                ('marca_2', models.BooleanField(default=False, verbose_name='Marca 2')),
                ('marca_3', models.BooleanField(default=False, verbose_name='Marca 3')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('clase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.clase', verbose_name='Clase')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.estadocivil', verbose_name='Estado civil')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.grupo', verbose_name='Grupo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miembros.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Hermano',
                'verbose_name_plural': 'Hermanos',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
