# Generated by Django 5.1.3 on 2025-12-12 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Don')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('icono', models.CharField(blank=True, help_text='Ej: bi-music-note, bi-book, bi-heart', max_length=50, verbose_name='Icono Bootstrap')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='hermano',
            name='anio_bautismo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de bautismo'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='apellido_soltera',
            field=models.CharField(blank=True, help_text='Apellido de nacimiento (opcional, para búsquedas)', max_length=200, verbose_name='Apellido de soltera'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='hermanos/', verbose_name='Foto de perfil'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ocupación/Profesión'),
        ),
        migrations.AlterField(
            model_name='hermano',
            name='celular',
            field=models.CharField(blank=True, help_text='Formato: +54 9 351 1234567', max_length=25, validators=[django.core.validators.RegexValidator(message='Ingrese un número válido. Ej: +54 9 351 1234567 o 351 1234567', regex='^\\+?54?\\s?9?\\s?\\d{2,4}\\s?\\d{6,8}$')], verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='hermano',
            name='dones',
            field=models.ManyToManyField(blank=True, help_text='Seleccione uno o más dones', to='miembros.don', verbose_name='Dones'),
        ),
    ]
