# Generated by Django 5.1.3 on 2025-12-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_add_new_fields_hermano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provincia',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AddField(
            model_name='provincia',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
