# Generated by Django 5.1.3 on 2025-12-15 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('code', models.CharField(max_length=6, verbose_name='Código')),
                ('verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('expires_at', models.DateTimeField(verbose_name='Expira')),
                ('attempts', models.IntegerField(default=0, verbose_name='Intentos')),
            ],
            options={
                'verbose_name': 'Verificación de Teléfono',
                'verbose_name_plural': 'Verificaciones de Teléfono',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ICEChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('agent_thread_id', models.CharField(blank=True, max_length=100, verbose_name='ID Thread del Agente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Sesión de Chat',
                'verbose_name_plural': 'Sesiones de Chat',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['session_id'], name='chat_icecha_session_12fece_idx'), models.Index(fields=['phone'], name='chat_icecha_phone_1d3f2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ICEChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente')], max_length=10, verbose_name='Rol')),
                ('message_type', models.CharField(choices=[('text', 'Texto'), ('audio', 'Audio')], default='text', max_length=10, verbose_name='Tipo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('audio_url', models.URLField(blank=True, verbose_name='URL del Audio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.icechatsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['created_at'],
            },
        ),
    ]
