# Generated by Django 5.1.3 on 2025-11-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('ip', models.GenericIPAddressField(verbose_name='Dirección IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('navegador', models.CharField(blank=True, max_length=100, verbose_name='Navegador')),
                ('sistema_operativo', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operativo')),
                ('dispositivo', models.CharField(blank=True, max_length=50, verbose_name='Dispositivo')),
                ('pais', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('url', models.CharField(max_length=500, verbose_name='URL visitada')),
                ('referrer', models.CharField(blank=True, max_length=500, verbose_name='Referencia')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='panel_visit_fecha_45b2b6_idx'), models.Index(fields=['ip'], name='panel_visit_ip_d0cd42_idx')],
            },
        ),
    ]
