# Generated by Django 5.1.3 on 2025-12-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Región/Provincia'),
        ),
    ]
