# Generated by Django 5.1.3 on 2026-02-13 14:53

import django.db.models.deletion
import encuestas.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('codigo', models.CharField(default=encuestas.models.generar_codigo, max_length=6, unique=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('activa', 'Activa'), ('en_vivo', 'En Vivo'), ('finalizada', 'Finalizada')], default='borrador', max_length=20)),
                ('pregunta_actual', models.PositiveIntegerField(default=0)),
                ('mostrar_resultados', models.BooleanField(default=False)),
                ('rango_excelente', models.PositiveIntegerField(default=85, help_text="Porcentaje mínimo para 'Excelente'")),
                ('rango_bueno', models.PositiveIntegerField(default=70, help_text="Porcentaje mínimo para 'Bueno'")),
                ('rango_regular', models.PositiveIntegerField(default=55, help_text="Porcentaje mínimo para 'Regular'")),
                ('rango_bajo', models.PositiveIntegerField(default=40, help_text="Porcentaje mínimo para 'Bajo'")),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('pregunta_actual', models.PositiveIntegerField(default=0)),
                ('conectado', models.BooleanField(default=True)),
                ('ultima_actividad', models.DateTimeField(auto_now=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='encuestas.encuesta')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('etiqueta_1', models.CharField(default='Todavía no hemos pensado en eso', max_length=100)),
                ('etiqueta_2', models.CharField(default='Apenas comenzando', max_length=100)),
                ('etiqueta_3', models.CharField(default='En progreso', max_length=100)),
                ('etiqueta_4', models.CharField(default='Bien encaminados', max_length=100)),
                ('etiqueta_5', models.CharField(default='En excelente forma', max_length=100)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='encuestas.encuesta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.participante')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['creado'],
                'unique_together': {('participante', 'pregunta')},
            },
        ),
    ]
