# Generated by Django 5.1.3 on 2026-02-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='bonus_tiempo',
            field=models.BooleanField(default=True, help_text='Bonus por responder rápido'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='puntos_base',
            field=models.PositiveIntegerField(default=100, help_text='Puntos por respuesta correcta'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tiempo_limite',
            field=models.PositiveIntegerField(default=30, help_text='Segundos para responder (trivia)'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='tipo',
            field=models.CharField(choices=[('opinion', 'Encuesta de Opinión'), ('trivia', 'Trivia/Quiz con Puntos'), ('votacion', 'Votación/Ranking')], default='opinion', max_length=20),
        ),
        migrations.AddField(
            model_name='participante',
            name='puntos_totales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='racha_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='respuestas_correctas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='activada_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='imagen_url',
            field=models.URLField(blank=True, help_text='URL de imagen para la pregunta'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opcion_a',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opcion_b',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opcion_c',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='opcion_d',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuesta_correcta',
            field=models.CharField(blank=True, choices=[('A', 'Opción A'), ('B', 'Opción B'), ('C', 'Opción C'), ('D', 'Opción D')], max_length=1),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tiempo_limite_custom',
            field=models.PositiveIntegerField(blank=True, help_text='Segundos (deja vacío para usar el general)', null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='es_correcta',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='opcion_elegida',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='puntos_obtenidos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='respuesta',
            name='tiempo_respuesta',
            field=models.FloatField(blank=True, help_text='Segundos que tardó en responder', null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='valor',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
    ]
