# Generated by Django 5.1.3 on 2026-02-15 22:47

import random
import encuestas.models
from django.db import migrations, models


# Letras fáciles de distinguir (sin I, L, O, 0, 1)
LETRAS_CODIGO = 'ABCDEFGHJKMNPQRSTUVWXYZ'


def actualizar_codigos_existentes(apps, schema_editor):
    """Genera nuevos códigos de 4 caracteres para encuestas existentes."""
    Encuesta = apps.get_model('encuestas', 'Encuesta')
    codigos_usados = set()

    for encuesta in Encuesta.objects.all():
        # Generar código único de 4 caracteres
        while True:
            nuevo_codigo = ''.join(random.choices(LETRAS_CODIGO, k=4))
            if nuevo_codigo not in codigos_usados:
                codigos_usados.add(nuevo_codigo)
                encuesta.codigo = nuevo_codigo
                encuesta.save()
                break


def revertir_codigos(apps, schema_editor):
    """No se puede revertir automáticamente los códigos."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_add_tipo_trivia_votacion'),
    ]

    operations = [
        # Primero actualizar los códigos existentes a 4 caracteres
        migrations.RunPython(actualizar_codigos_existentes, revertir_codigos),
        # Luego cambiar el campo
        migrations.AlterField(
            model_name='encuesta',
            name='codigo',
            field=models.CharField(default=encuestas.models.generar_codigo, max_length=4, unique=True),
        ),
    ]
